import { Activity, CheckCircle2, Clock3, KeyRound, LogIn, LogOut, MailCheck, ShieldCheck, Trash2, UserPlus } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { Alert, Button } from "../components/ui";
import { useAuth } from "../context/AuthContext";
import { formatDate, formatDateTime } from "../utils/auth";
const iconMap = { login: LogIn, register: UserPlus, email: MailCheck, otp: ShieldCheck, password: KeyRound, logout: LogOut, extend: Clock3, profile: UserPlus, session: Activity };
export default function ActivityPage() { const { getActivities, clearActivities, currentUser } = useAuth(); const [cleared, setCleared] = useState(false); const activities = getActivities(); return <DashboardLayout><div className="mx-auto max-w-[980px]"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link to="/dashboard" className="mb-4 inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-coral">← Back to dashboard</Link><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-coral">Security history</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-[-0.05em] text-ink">Activity</h1><p className="mt-2 text-sm text-slate-500">A local timeline of important account and security events.</p></div><Button variant="outline" onClick={() => { clearActivities(); setCleared(true); }} disabled={!activities.length}><Trash2 size={15} />Clear activity</Button></div>{cleared && <Alert variant="success" className="mt-5">Activity history cleared from this browser.</Alert>}<section className="mt-8 rounded-2xl bg-white p-6 shadow-[0_10px_30px_rgba(10,23,55,0.04)] ring-1 ring-ink/[0.05] sm:p-8">{activities.length ? <div className="relative space-y-0 before:absolute before:bottom-5 before:left-[19px] before:top-5 before:w-px before:bg-ink/[0.08]">{activities.map((event) => { const Icon = iconMap[event.type] || CheckCircle2; return <div key={event.id} className="relative flex gap-4 py-4 first:pt-0 last:pb-0"><span className="relative z-10 grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#f5f7fb] text-coral ring-4 ring-white"><Icon size={17} /></span><div className="min-w-0 flex-1"><div className="flex flex-col justify-between gap-1 sm:flex-row sm:items-center"><h2 className="text-sm font-semibold text-ink">{event.title}</h2><time className="text-xs text-slate-400" dateTime={event.createdAt}>{formatDateTime(event.createdAt)}</time></div><p className="mt-1 text-xs leading-5 text-slate-500">{event.detail}</p></div></div>; })}</div> : <div className="py-14 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-coral/10 text-coral"><Activity size={24} /></span><h2 className="mt-5 font-display text-xl font-semibold text-ink">No activity yet</h2><p className="mx-auto mt-2 max-w-[340px] text-sm leading-6 text-slate-500">Important events for {currentUser?.email || "your account"} will appear here as you use Northstar.</p></div>}</section><p className="mt-4 text-xs text-slate-400">All timestamps use your browser’s local timezone. Today is {formatDate(new Date())}.</p></div></DashboardLayout>; }
