import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { DEMO_MODE, STORAGE_KEYS, normalizeEmail, readJson, removeStored, writeJson } from "../utils/auth";
export const sessionConfig = { durationMs: 10 * 60 * 1000, warningMs: 60 * 1000, otpDurationSeconds: 90, resendCooldownSeconds: 30 };
export const demoCredentials = { email: "demo@example.com", password: "Demo@123", name: "Demo Workspace" };
const AuthContext = createContext(null); const wait = (ms) => new Promise((resolve) => window.setTimeout(resolve, ms));
function readUsers() { return readJson(localStorage, STORAGE_KEYS.users, []); } function writeUsers(users) { writeJson(localStorage, STORAGE_KEYS.users, users); }
function seedDemoUser() { const users = readUsers(); if (users.some((user) => user.email === demoCredentials.email)) return users; const seeded = [{ id: "demo-user", name: demoCredentials.name, email: demoCredentials.email, password: demoCredentials.password, isVerified: true, createdAt: new Date().toISOString() }, ...users]; writeUsers(seeded); return seeded; }
function findUser(email) { return seedDemoUser().find((user) => user.email === normalizeEmail(email)); }
function storedSession() { const value = readJson(localStorage, STORAGE_KEYS.session) || readJson(sessionStorage, STORAGE_KEYS.session); if (!value?.user || value.expiresAt <= Date.now()) { removeStored(STORAGE_KEYS.session); removeStored(STORAGE_KEYS.currentUser); return null; } return value; }
function recordToStorage(type, title, detail, userEmail = "") { const activities = readJson(localStorage, STORAGE_KEYS.activities, []); const event = { id: `activity-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, type, title, detail, email: userEmail, createdAt: new Date().toISOString() }; writeJson(localStorage, STORAGE_KEYS.activities, [event, ...activities].slice(0, 100)); const notifications = readJson(localStorage, STORAGE_KEYS.notifications, []); writeJson(localStorage, STORAGE_KEYS.notifications, [{ ...event, read: false }, ...notifications].slice(0, 50)); return event; }
export function AuthProvider({ children }) {
  const initial = storedSession(); const [currentUser, setCurrentUser] = useState(initial?.user || null); const [session, setSession] = useState(initial || null); const [pendingEmail, setPendingEmail] = useState(() => localStorage.getItem(STORAGE_KEYS.pendingEmail) || ""); const [clock, setClock] = useState(Date.now()); const [dataVersion, setDataVersion] = useState(0);
  useEffect(() => { const id = window.setInterval(() => setClock(Date.now()), 1000); return () => window.clearInterval(id); }, []);
  const refreshData = useCallback(() => setDataVersion((value) => value + 1), []); const remainingMs = session?.expiresAt ? Math.max(0, session.expiresAt - clock) : 0; const sessionExpired = Boolean(session && remainingMs <= 0); const sessionWarning = Boolean(session && remainingMs > 0 && remainingMs <= sessionConfig.warningMs);
  const clearSession = useCallback((logEvent = true) => { if (logEvent && currentUser) recordToStorage("logout", "Logged out", "Session ended securely.", currentUser.email); removeStored(STORAGE_KEYS.session); removeStored(STORAGE_KEYS.currentUser); setCurrentUser(null); setSession(null); refreshData(); }, [currentUser, refreshData]); useEffect(() => { if (sessionExpired) clearSession(); }, [sessionExpired, clearSession]);
  const setAuthSession = useCallback((user, remember = true, activityType = null) => { const next = { user, remember, startedAt: new Date().toISOString(), expiresAt: Date.now() + sessionConfig.durationMs }; removeStored(STORAGE_KEYS.session); writeJson(remember ? localStorage : sessionStorage, STORAGE_KEYS.session, next); writeJson(localStorage, STORAGE_KEYS.currentUser, user); setCurrentUser(user); setSession(next); if (activityType === "login") recordToStorage("login", "Successful login", "Signed in with password.", user.email); if (activityType === "extend") recordToStorage("extend", "Session extended", "Session timer refreshed.", user.email); refreshData(); }, [refreshData]);
  const login = async (email, password, remember = false) => { await wait(450); const user = findUser(email); if (!user || user.password !== password) throw new Error("The email or password you entered is incorrect."); if (!user.isVerified) throw new Error("Please verify your email before signing in."); setAuthSession(user, remember, "login"); return user; };
  const register = async ({ name, email, password }) => { await wait(450); const normalized = normalizeEmail(email); const users = seedDemoUser(); if (users.some((user) => user.email === normalized)) throw new Error("An account with this email already exists."); const user = { id: `user-${Date.now()}`, name: name.trim(), email: normalized, password, isVerified: false, createdAt: new Date().toISOString() }; writeUsers([user, ...users]); localStorage.setItem(STORAGE_KEYS.pendingEmail, normalized); setPendingEmail(normalized); recordToStorage("register", "Account created", "Northstar workspace created.", normalized); refreshData(); return user; };
  const updateUser = (updatedUser, activityType = null) => { const users = seedDemoUser().map((user) => user.id === updatedUser.id ? updatedUser : user); writeUsers(users); writeJson(localStorage, STORAGE_KEYS.currentUser, updatedUser); setCurrentUser(updatedUser); if (session) { const next = { ...session, user: updatedUser }; writeJson(session.remember ? localStorage : sessionStorage, STORAGE_KEYS.session, next); setSession(next); } const activity = { profile: ["profile", "Profile updated"], password: ["password", "Password changed"], otp: ["otp", "OTP verification completed"], email: ["email", "Email verified"] }[activityType]; if (activity) recordToStorage(activity[0], activity[1], "Account details were updated securely.", updatedUser.email); refreshData(); return updatedUser; };
  const verifyEmail = (email) => { const user = findUser(email); if (!user) throw new Error("This verification link is no longer valid."); const updated = { ...user, isVerified: true }; updateUser(updated, "email"); localStorage.removeItem(STORAGE_KEYS.pendingEmail); setPendingEmail(""); setAuthSession(updated, true); return updated; };
  const requestOtp = useCallback(async (email) => { await wait(350); const normalized = normalizeEmail(email); const code = String(Math.floor(100000 + Math.random() * 900000)); const otp = { email: normalized, code, createdAt: new Date().toISOString(), expiresAt: Date.now() + sessionConfig.otpDurationSeconds * 1000 }; writeJson(sessionStorage, STORAGE_KEYS.otp, otp); refreshData(); return otp; }, [refreshData]);
  const getOtp = useCallback((email) => { const otp = readJson(sessionStorage, STORAGE_KEYS.otp); return otp?.email === normalizeEmail(email) ? otp : null; }, []);
  const verifyOtp = async (email, code) => { await wait(250); const otp = getOtp(email); if (!otp || otp.expiresAt <= Date.now()) throw new Error("This OTP has expired. Request a new code."); if (otp.code !== code) throw new Error("That OTP is incorrect. Check the six digits and try again."); const user = findUser(email); if (!user) throw new Error("We could not find that Northstar account."); const updated = { ...user, isVerified: true }; updateUser(updated, "otp"); sessionStorage.removeItem(STORAGE_KEYS.otp); if (!currentUser) setAuthSession(updated, true); return updated; };
  const resendOtp = (email) => requestOtp(email); const resendVerification = async (email) => { await wait(350); return normalizeEmail(email); };
  const requestPasswordReset = async (email) => { await wait(350); const normalized = normalizeEmail(email); if (!findUser(normalized)) throw new Error("We couldn't find an account with that email address."); writeJson(localStorage, STORAGE_KEYS.reset, { email: normalized, createdAt: Date.now() }); return normalized; };
  const resetPassword = async (password) => { await wait(350); const request = readJson(localStorage, STORAGE_KEYS.reset); if (!request || Date.now() - request.createdAt > 15 * 60 * 1000) throw new Error("This reset request has expired. Start again from Forgot password."); const user = findUser(request.email); updateUser({ ...user, password }, "password"); localStorage.removeItem(STORAGE_KEYS.reset); };
  const changePassword = async (password) => { await wait(350); if (!currentUser) throw new Error("You must be signed in to change your password."); updateUser({ ...currentUser, password }, "password"); };
  const updateProfile = async ({ name, email }) => { await wait(300); if (!currentUser) throw new Error("You must be signed in to edit your profile."); const normalized = normalizeEmail(email); const conflict = seedDemoUser().some((user) => user.email === normalized && user.id !== currentUser.id); if (conflict) throw new Error("That email is already used by another account."); return updateUser({ ...currentUser, name: name.trim(), email: normalized }, "profile"); };
  const getActivities = () => readJson(localStorage, STORAGE_KEYS.activities, []); const clearActivities = () => { localStorage.removeItem(STORAGE_KEYS.activities); refreshData(); }; const getNotifications = () => readJson(localStorage, STORAGE_KEYS.notifications, []); const markNotificationsRead = () => { writeJson(localStorage, STORAGE_KEYS.notifications, getNotifications().map((item) => ({ ...item, read: true }))); refreshData(); }; const stayLoggedIn = () => { if (currentUser) setAuthSession(currentUser, session?.remember ?? true, "extend"); };
  const value = useMemo(() => ({ currentUser, isAuthenticated: Boolean(currentUser && session), pendingEmail, login, register, logout: clearSession, verifyEmail, requestOtp, resendOtp, getOtp, verifyOtp, resendVerification, requestPasswordReset, resetPassword, changePassword, updateProfile, getActivities, clearActivities, getNotifications, markNotificationsRead, stayLoggedIn, demoCredentials, DEMO_MODE, sessionConfig, dataVersion, session: session ? { ...session, remainingMs, remainingSeconds: Math.ceil(remainingMs / 1000), showWarning: sessionWarning } : null }), [currentUser, session, pendingEmail, dataVersion, remainingMs, sessionWarning, login, register, clearSession, verifyEmail, requestOtp, resendOtp, getOtp, verifyOtp, stayLoggedIn]);
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
export function useAuth() { const value = useContext(AuthContext); if (!value) throw new Error("useAuth must be used inside AuthProvider"); return value; }
