import { Check, Eye, EyeOff, Fingerprint, Loader2, Sparkles } from "lucide-react";
import { forwardRef, useState } from "react";
import { Link } from "react-router-dom";

export function BrandMark({ compact = false }) {
  return <Link to="/login" aria-label="Northstar home" className="group inline-flex items-center gap-3"><span className="brand-mark relative grid h-10 w-10 place-items-center rounded-[13px] text-white shadow-[0_10px_30px_rgba(255,111,97,0.24)]"><Sparkles size={19} strokeWidth={2.2} /></span>{!compact && <span className="font-display text-[16px] font-bold tracking-[0.12em] text-white">NORTHSTAR</span>}</Link>;
}
export const Button = forwardRef(function Button({ children, className = "", variant = "primary", loading = false, type = "button", ...props }, ref) { const variants = { primary: "bg-coral text-[#fffaf8] shadow-[0_10px_24px_rgba(255,111,97,0.22)] hover:bg-[#ff8173]", secondary: "bg-white/[0.07] text-white ring-1 ring-inset ring-white/[0.12] hover:bg-white/[0.12]", subtle: "bg-transparent text-slate-300 hover:bg-white/[0.06] hover:text-white", outline: "bg-transparent text-slate-200 ring-1 ring-inset ring-white/[0.14] hover:bg-white/[0.07]", dark: "bg-ink text-white shadow-[0_10px_24px_rgba(8,17,38,0.18)] hover:bg-[#172b55]", danger: "bg-[#dc5c63] text-white hover:bg-[#ea6a70]" }; return <button ref={ref} type={type} className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition duration-200 ease-out active:scale-[.97] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-coral/25 disabled:cursor-not-allowed disabled:opacity-60 ${variants[variant] || variants.primary} ${className}`} disabled={loading || props.disabled} {...props}>{loading && <Loader2 size={16} className="animate-spin" aria-hidden="true" />}{children}</button>; });
export const Input = forwardRef(function Input({ label, error, hint, className = "", id, ...props }, ref) { return <div className="space-y-2">{label && <label htmlFor={id} className="block text-[12px] font-semibold uppercase tracking-[0.13em] text-slate-400">{label}</label>}<input ref={ref} id={id} aria-invalid={Boolean(error)} className={`h-12 w-full rounded-xl border border-white/[0.12] bg-[#101d3a]/70 px-4 text-[15px] text-white outline-none transition placeholder:text-slate-600 focus:border-coral/70 focus:bg-[#122345] focus:ring-4 focus:ring-coral/10 ${error ? "border-[#f18186]" : ""} ${className}`} {...props} />{error && <p className="text-xs font-medium text-[#ff9b9f]">{error}</p>}{!error && hint && <p className="text-xs text-slate-500">{hint}</p>}</div>; });
export function PasswordInput({ label = "Password", error, hint, id = "password", ...props }) { const [visible, setVisible] = useState(false); return <div className="space-y-2">{label && <label htmlFor={id} className="block text-[12px] font-semibold uppercase tracking-[0.13em] text-slate-400">{label}</label>}<div className="relative"><input id={id} type={visible ? "text" : "password"} aria-invalid={Boolean(error)} className={`h-12 w-full rounded-xl border border-white/[0.12] bg-[#101d3a]/70 px-4 pr-12 text-[15px] text-white outline-none transition placeholder:text-slate-600 focus:border-coral/70 focus:bg-[#122345] focus:ring-4 focus:ring-coral/10 ${error ? "border-[#f18186]" : ""}`} {...props} /><button type="button" onClick={() => setVisible((value) => !value)} aria-label={visible ? "Hide password" : "Show password"} className="absolute right-2 top-1/2 grid h-9 w-9 -translate-y-1/2 place-items-center rounded-lg text-slate-500 transition hover:bg-white/[0.06] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-coral/50">{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></div>{error && <p className="text-xs font-medium text-[#ff9b9f]">{error}</p>}{!error && hint && <p className="text-xs text-slate-500">{hint}</p>}</div>; }
export function Alert({ children, variant = "error", className = "" }) { const styles = { error: "border-[#f18186]/25 bg-[#a1434b]/10 text-[#ffb0b3]", success: "border-mint/25 bg-mint/10 text-[#b1f5d8]", info: "border-sky/25 bg-sky/10 text-[#b9e8ff]" }; return <div role="alert" aria-live="polite" className={`animate-[fade-up_220ms_ease-out] rounded-xl border px-4 py-3 text-sm leading-6 ${styles[variant] || styles.info} ${className}`}>{children}</div>; }
export function Spinner({ size = 18 }) { return <Loader2 size={size} className="animate-spin text-coral" />; }
export function CheckItem({ children, active }) { return <li className={`flex items-center gap-2 text-xs transition ${active ? "text-mint" : "text-slate-500"}`}><span className={`grid h-4 w-4 place-items-center rounded-full ${active ? "bg-mint/15" : "bg-white/[0.06]"}`}>{active ? <Check size={11} strokeWidth={3} /> : <span className="h-1 w-1 rounded-full bg-current" />}</span>{children}</li>; }
export { Fingerprint };
